theme: jekyll-theme-time-machine

title: Reasoning Agents Project Website
description: "Website version of the project report"
permalink: /:year/:month/:day/:title/

show_downloads: "false"
plugins: ['jekyll/scholar']
scholar:
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  bibliography: bibliography.bib

  query: "@*"