theme: jekyll-theme-time-machine

title: Reasoning Agents Project Website
description: "We present here our work investigating the effects of Reward Shaping on a Hierarchical Reinforcement Learning (HRL) environment while specifying increasingly complex temporal goals defined as LTL$_f$ formulas. Thanks to the flexibility of the LTL$_f$ language, it is trivial to define such goals and, thanks to existing Python libraries, convert them to DFA automatons that work best with RL tasks.
    
    We also investigate the possibility to discard the LTL$_f$ goals and instead redefine the environment using STRIPS, which could later be extended to accept a multitude of temporal goals implicitly. "
permalink: /:year/:month/:day/:title/

show_downloads: "true"